### ISSUE TITLE
Create the codeConnects program view

### ISSUE THREAD

**Issue by bibekg** [the-coding-school/the-cs#65]
As part of the programs page redesign, we want to create four different UI views for each program TCS offers. The program selection UI is still under work but the main framework for routing between the views is already there in the `programs-page-redesign` branch **(which you should branch off of when starting work on this issue!)** The program selector looks like this, and the program view you work on will appear below it, like this. A link to the design for what you'll work on is below the image.
![6baea775-8bf5-4675-9280-ab297a00e56b](https://user-images.githubusercontent.com/8083680/30664075-5b41795c-9e01-11e7-8341-5e4e75a916e4.jpeg)

[Design](https://files.slack.com/files-pri/T07JES2F7-F75KBJR6H/our_programs_mockup_2_codeconnects.pdf) | [Assets](https://files.slack.com/files-pri/T07JES2F7-F72HW9TJ7/programspagecontent.zip) 
_For this issue/view, create only the content below the title and slogan._

**Comment by zacharysang** [comment]
@bibekg 
I want to clarify the requirements for this: I am to just create the CodeConnects program view (this is all that was included in the mockup)? Either way, do we expect the other programs views to eventually follow a similar layout or will each program view need a separate component? 

Also, are we happy with the how our list of problems is laid out? The way that 2 doesn't follow the same layout as 1 and 3 might be visually confusing. 

Here is an image to highlight what I'm referring to:

![image](https://user-images.githubusercontent.com/17336621/33232889-e64ac20c-d1db-11e7-910f-9625f4118842.png)

**Comment by bibekg** [comment]
Good call. I think making the format of #2 match the others would be better. Maybe we could alternate the order of the title and the description to keep it from being too monotonous. So for #2, `2) Many Underrepresented Groups` appears on the right, and its description text appears on the left.

And yeah, this issue is just for creating this particular codeConnects program view. If you look [here](https://github.com/the-coding-school/the-cs/tree/programs-page-redesign/src/pages/OurProgramsPage) on the `programs-page-redesign` branch, you'll see that we already have a framework for switching between the views, but just need each individual view completed. So the codeConnects view would go [here](https://github.com/the-coding-school/the-cs/tree/programs-page-redesign/src/pages/OurProgramsPage/ProgramViews/CodeConnectsView).

**Comment by zacharysang** [comment]
Okay, yeah that sounds good. Do we expect the different program views to be very different in structure? Or should I be trying to make this view component for codeConnects generic enough to be potentially reused?

Also, I think I am missing some assets for the icons for the different icons in each of the 3 approaches, and then also the 3 icons at the bottom of the mockup (the calendar, book and then the wrench-crossed-with-pencil). I don't these were included in the attached mockups, but are they included somewhere else in the project that I'm missing?

**Comment by bibekg** [comment]
Don't worry too much about making it generic, I believe the other views are a bit distinct. For the icons, just use placeholder images (maybe from http://placehold.it) for now since our designer is unavailable at the moment.
